pipeline:
  publish:
    image: plugins/docker
    repo: pingu/smashing-gitlab
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: [ master, develop ]
