export APOLLO_API_HOST=http://localhost:6425
export DASHARAMA_SERVER_API_HOST=http://localhost:3000
export GITLAB_HOST=${GITLAB_HOST}
export GITLAB_PRIVATE_ACCESS_TOKEN=${GITLAB_PRIVATE_ACCESS_TOKEN}
export DASHARAMA_AUTH_TOKEN=${DASHARAMA_AUTH_TOKEN}
